services:
  mysql:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: GoTechTigers!
      MYSQL_USER: web
      MYSQL_PASSWORD: AGoodPassword
    container_name: mysql
    ports: 
      - 3306:3306
  
  phpMyAdmin: 
    image: phpmyadmin 
    environment: 
      PMA_HOST: mysql
      PMA_USER: root 
      PMA_PASSWORD: GoTechTigers!
    container_name: phpMyAdmin
    ports: 
      - 8080:80 
