
services:
  mysql:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: GoTechMavs!
    expose: 
      - 3306
  
  phpMyAdmin: 
    image: phpmyadmin 
    environment: 
      PMA_HOST: mysql
      PMA_USER: root 
      PMA_PASSWORD: GoTechMavs!
    ports: 
      - 8080:80 

