
services:
  mysql:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: GoTechMavs!
    expose: 
      - 3306
  
  phpMyAdmin: 
    image: phpmyadmin 
    environment: 
      PMA_ARBITRARY: 1
    ports: 
      - 8080:80 

