
services:
  mysql:
    image: mysql:8.2
    environment: 
      MYSQL_ROOT_PASSWORD: GoTechMavs!
      MYSQL_USER: web
      MYSQL_PASSWORD: AGoodPassword
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3306:3306
  
  phpMyAdmin: 
    image: phpmyadmin 
    environment: 
      PMA_HOST: mysql
      PMA_USER: root 
      PMA_PASSWORD: GoTechMavs!
    ports: 
      - 8080:80 

